osx_image: xcode10.0
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
  - gem install cocoapods
  - pod install --project-directory=Example
script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/LDATools.xcworkspace -scheme LDATools-Example -sdk iphonesimulator12.0 ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint
