osx_image: xcode10.0
language: objective-c
cache: cocoapods
podfile: Example/Podfile
xcode_destination: platform=iOS Simulator,OS=11.4,name=iPhone X
xcode_scheme: LDATools-Example
xcode_project: Example/LDATools.xcworkspace
before_install:
  - gem install cocoapods
  - pod install --project-directory=Example
  - gem update cocoapods
script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/LDATools.xcworkspace -scheme LDATools-Example -sdk iphonesimulator test | xcpretty
