osx_image: xcode10.0
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
  - gem install cocoapods
  - pod install --project-directory=Example
script:
  - xcrun simctl list
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/LDATools.xcworkspace -scheme LDATools-Example -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.2' | xcpretty
  - pod lib lint --verbose
